### ISSUE TITLE
Filename is displayed after closing file

### ISSUE THREAD

**Issue by NickAcPT** [Swan/discord-rpc-vs#1]
I really like this extension. It's awesome.
One thing I noted while testing:
If I open file X.cs and then do my normal coding, the Rich Presence updates accordingly, but when I close the file (tab), it continues counting and showing the file name on Discord.

This was the only bug I found while using it.
Congratulations to the developer.

**Comment by NickAcPT** [comment]
Closing issue because I'm an idiot.

**Comment by Swan** [comment]
No problem. Let me know if there's any issues that you find in the future.
